{{- if and .Values.imagePullSecret.name .Values.imagePullSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: {{ dict "auths" (dict "ghcr.io" (dict "username" .Values.docker.username "password" .Values.docker.password "email" .Values.docker.email "auth" (printf "%s:%s" .Values.docker.username .Values.docker.password | b64enc))) | toJson | quote }}
{{- end }}
