{{- $name := printf "%s-backend" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.servicePort }}
  type: ClusterIP
