{{- $name := printf "%s-frontend" .Release.Name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-svc
  labels:
    app: {{ $name }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.containerPort }}
  type: ClusterIP
